#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class MetricsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRegistry(Registry instance);
    partial void UpdateRegistry(Registry instance);
    partial void DeleteRegistry(Registry instance);
    partial void InsertIpAddress(IpAddress instance);
    partial void UpdateIpAddress(IpAddress instance);
    partial void DeleteIpAddress(IpAddress instance);
    partial void InsertMacAddress(MacAddress instance);
    partial void UpdateMacAddress(MacAddress instance);
    partial void DeleteMacAddress(MacAddress instance);
    #endregion
		
		public MetricsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MetricsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MetricsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MetricsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Registry> Registries
		{
			get
			{
				return this.GetTable<Registry>();
			}
		}
		
		public System.Data.Linq.Table<IpAddress> IpAddresses
		{
			get
			{
				return this.GetTable<IpAddress>();
			}
		}
		
		public System.Data.Linq.Table<MacAddress> MacAddresses
		{
			get
			{
				return this.GetTable<MacAddress>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Registry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private ushort _Event;
		
		private string _WindowTitle;
		
		private string _ExeModulePath;
		
		private string _ProcessName;
		
		private System.DateTime _Time;
		
		private long _Ip;
		
		private long _Mac;
		
		private EntityRef<IpAddress> _IpAddress;
		
		private EntityRef<MacAddress> _MacAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnEventChanging(ushort value);
    partial void OnEventChanged();
    partial void OnWindowTitleChanging(string value);
    partial void OnWindowTitleChanged();
    partial void OnExeModulePathChanging(string value);
    partial void OnExeModulePathChanged();
    partial void OnProcessNameChanging(string value);
    partial void OnProcessNameChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnIpChanging(long value);
    partial void OnIpChanged();
    partial void OnMacChanging(long value);
    partial void OnMacChanged();
    #endregion
		
		public Registry()
		{
			this._IpAddress = default(EntityRef<IpAddress>);
			this._MacAddress = default(EntityRef<MacAddress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event")]
		public ushort Event
		{
			get
			{
				return this._Event;
			}
			set
			{
				if ((this._Event != value))
				{
					this.OnEventChanging(value);
					this.SendPropertyChanging();
					this._Event = value;
					this.SendPropertyChanged("Event");
					this.OnEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindowTitle", CanBeNull=false)]
		public string WindowTitle
		{
			get
			{
				return this._WindowTitle;
			}
			set
			{
				if ((this._WindowTitle != value))
				{
					this.OnWindowTitleChanging(value);
					this.SendPropertyChanging();
					this._WindowTitle = value;
					this.SendPropertyChanged("WindowTitle");
					this.OnWindowTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExeModulePath", CanBeNull=false)]
		public string ExeModulePath
		{
			get
			{
				return this._ExeModulePath;
			}
			set
			{
				if ((this._ExeModulePath != value))
				{
					this.OnExeModulePathChanging(value);
					this.SendPropertyChanging();
					this._ExeModulePath = value;
					this.SendPropertyChanged("ExeModulePath");
					this.OnExeModulePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessName", CanBeNull=false)]
		public string ProcessName
		{
			get
			{
				return this._ProcessName;
			}
			set
			{
				if ((this._ProcessName != value))
				{
					this.OnProcessNameChanging(value);
					this.SendPropertyChanging();
					this._ProcessName = value;
					this.SendPropertyChanged("ProcessName");
					this.OnProcessNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ip")]
		public long Ip
		{
			get
			{
				return this._Ip;
			}
			set
			{
				if ((this._Ip != value))
				{
					if (this._IpAddress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIpChanging(value);
					this.SendPropertyChanging();
					this._Ip = value;
					this.SendPropertyChanged("Ip");
					this.OnIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mac")]
		public long Mac
		{
			get
			{
				return this._Mac;
			}
			set
			{
				if ((this._Mac != value))
				{
					if (this._MacAddress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMacChanging(value);
					this.SendPropertyChanging();
					this._Mac = value;
					this.SendPropertyChanged("Mac");
					this.OnMacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IpAddress_Registry", Storage="_IpAddress", ThisKey="Ip", OtherKey="Id", IsForeignKey=true)]
		public IpAddress IpAddress
		{
			get
			{
				return this._IpAddress.Entity;
			}
			set
			{
				IpAddress previousValue = this._IpAddress.Entity;
				if (((previousValue != value) 
							|| (this._IpAddress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._IpAddress.Entity = null;
						previousValue.Registries.Remove(this);
					}
					this._IpAddress.Entity = value;
					if ((value != null))
					{
						value.Registries.Add(this);
						this._Ip = value.Id;
					}
					else
					{
						this._Ip = default(long);
					}
					this.SendPropertyChanged("IpAddress");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MacAddress_Registry", Storage="_MacAddress", ThisKey="Mac", OtherKey="Id", IsForeignKey=true)]
		public MacAddress MacAddress
		{
			get
			{
				return this._MacAddress.Entity;
			}
			set
			{
				MacAddress previousValue = this._MacAddress.Entity;
				if (((previousValue != value) 
							|| (this._MacAddress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MacAddress.Entity = null;
						previousValue.Registries.Remove(this);
					}
					this._MacAddress.Entity = value;
					if ((value != null))
					{
						value.Registries.Add(this);
						this._Mac = value.Id;
					}
					else
					{
						this._Mac = default(long);
					}
					this.SendPropertyChanged("MacAddress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class IpAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Ip;
		
		private EntitySet<Registry> _Registries;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIpChanging(string value);
    partial void OnIpChanged();
    #endregion
		
		public IpAddress()
		{
			this._Registries = new EntitySet<Registry>(new Action<Registry>(this.attach_Registries), new Action<Registry>(this.detach_Registries));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ip", CanBeNull=false)]
		public string Ip
		{
			get
			{
				return this._Ip;
			}
			set
			{
				if ((this._Ip != value))
				{
					this.OnIpChanging(value);
					this.SendPropertyChanging();
					this._Ip = value;
					this.SendPropertyChanged("Ip");
					this.OnIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IpAddress_Registry", Storage="_Registries", ThisKey="Id", OtherKey="Ip")]
		public EntitySet<Registry> Registries
		{
			get
			{
				return this._Registries;
			}
			set
			{
				this._Registries.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registries(Registry entity)
		{
			this.SendPropertyChanging();
			entity.IpAddress = this;
		}
		
		private void detach_Registries(Registry entity)
		{
			this.SendPropertyChanging();
			entity.IpAddress = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class MacAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Mac;
		
		private EntitySet<Registry> _Registries;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMacChanging(string value);
    partial void OnMacChanged();
    #endregion
		
		public MacAddress()
		{
			this._Registries = new EntitySet<Registry>(new Action<Registry>(this.attach_Registries), new Action<Registry>(this.detach_Registries));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mac", CanBeNull=false)]
		public string Mac
		{
			get
			{
				return this._Mac;
			}
			set
			{
				if ((this._Mac != value))
				{
					this.OnMacChanging(value);
					this.SendPropertyChanging();
					this._Mac = value;
					this.SendPropertyChanged("Mac");
					this.OnMacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MacAddress_Registry", Storage="_Registries", ThisKey="Id", OtherKey="Mac")]
		public EntitySet<Registry> Registries
		{
			get
			{
				return this._Registries;
			}
			set
			{
				this._Registries.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registries(Registry entity)
		{
			this.SendPropertyChanging();
			entity.MacAddress = this;
		}
		
		private void detach_Registries(Registry entity)
		{
			this.SendPropertyChanging();
			entity.MacAddress = null;
		}
	}
}
#pragma warning restore 1591
